### ISSUE TITLE
καταπλέω issue

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/lsj#9]
καταπλέω shows up in the brief definition, but a click on the LSJ link gives the lemma but no entry.

**Comment by balmas** [comment]
this should be fixed now. Verification testing pending deployment of updated dictionary files.

**Comment by balmas** [comment]
@monzug this change has been made in the live lexicon service files.   Please verify whenever you have a chance. Thanks!

**Comment by monzug** [comment]
I still see the issue reported above. Maybe the LSJ dictionary hasn't been updated yet?

![Screen Shot 2020-12-11 at 5 14 04 PM](https://user-images.githubusercontent.com/41396793/101927196-7a8b7f00-3bd4-11eb-8883-9c3e94678c1a.png)

**Comment by monzug** [comment]
it was a cache issue, fixed with issue #10
